### ISSUE TITLE
PTZ Control got digest authentication error with hikvision camera 

### ISSUE THREAD

**Issue by sumonnwe** [jimm98y/SharpOnvif#11]
I am using Sharponvifclient and my camera itself as a server so don't run Sharponvifserver. From where, I got an issue when calling the PTZ control. The camera is also enabled onvif protocol and ptz is suppoted. Check with ONVIF DEVICE MANAGER got authentication issue even though I am using the same account of web login as there's no setting for new account specifically for PTZ. When running PTZ relativemoveasync got that error. 

Now I stuck with PTZClient Digest Header. The error is here.

System.ServiceModel.Security.MessageSecurityException: The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Digest qop="auth", realm="IP Camera(F1598)", nonce="4e446731597a466b4d7a45364e7a4930593249784e513d3d", stale="FALSE"'.
at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass2_0.b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location ---

**Comment by jimm98y** [comment]
Did you add the `DigestBehavior` to `ptzEndpoint.EndpointBehaviors`? Please see the `SetAuthentication` method in the ` SimpleOnvifClient`.

**Comment by sumonnwe** [comment]
![image](https://github.com/user-attachments/assets/2e610cab-fc61-45f1-ba90-bd910c3cd18b)

Yes, I added but got protocol error exception and 400 bad request.

**Comment by jimm98y** [comment]
Well, if it does not work with Onvif Device Manager, then it will not work with SharpOnvif. It looks to me like your camera does not support the `ContinuousMove` action. You should first query the capabilities of the camera and only call actions that are actually supported.
Please see https://github.com/jimm98y/SharpOnvif/issues/7 for a snippet using the `AbsoluteMove` and `RelativeMove` actions and see if they work with your camera.
If you make it work with Onvif Device Manager and the same call will fail in SharpOnvif, then please capture the calls from Onvif Device Manager as well as SharpOnvif using Wireshark and we can take a look and see what's going on.

**Comment by sumonnwe** [comment]
![ptz8](https://github.com/user-attachments/assets/fb394f29-894b-428f-9868-afb73cd0e06e)
![ptz2](https://github.com/user-attachments/assets/5359fd42-76c1-4a3b-9863-443e69d56bb8)

Query the capabilities, got the Digest authentication error. 
Check with ODM, got 404 Bad request either. So how can I proceed it? 
Can I change any setting and protocol at my hikvision camera DS-2DE3A404IW-DE/W. Actually I already enabled ONVIF, PTZ control? I am working on MainStream profile. 

![image](https://github.com/user-attachments/assets/9bf54ec4-47f9-4389-825b-38edec49a9a2)

**Comment by jimm98y** [comment]
Based off the error, it looks like the camera is forcing Digest in the HTTP Authorization header, while SharpOnvif (and Onvif Device Manager to my knowledge) only support WS-UsernameToken. 
Please see https://ipcamtalk.com/threads/onvif-problem-with-hikvision-dvr-the-http-request-is-unauthorized-with-client-authentication-scheme.42433/post-747891 for more info and perhaps a solution on how to configure the camera.
On SharpOnvif side, supporting Digest Authentication header according to RFC 2617 is an enhancement that would have to be implemented.
