### ISSUE TITLE
How use Server project

### ISSUE THREAD

**Issue by masgh021** [jimm98y/SharpOnvif#2]
Hello @jimm98y 
I want make my pc to onvif device and connect to other device via c# 
can you help ?
what are steps ?

after i run sharponvif i couldn't see my pc on local network via onvif device manager  ,
what should i do ?

**Comment by jimm98y** [comment]
You have to run SharpOnvifService in Visual Studio as Administrator. Then your PC should become discoverable by Onvif Device Manager.

**Comment by masgh021** [comment]
Thanks @jimm98y . I tested and my pc is discoverable .

**Comment by masgh021** [comment]
Hi @jimm98y 
please check this image . 
![photo_2024-09-26_19-53-55](https://github.com/user-attachments/assets/e8416f98-fe18-42ff-b464-d69ebd72a062)

 I want to add a sample video for test 
live-video and live-streaming But I can't .  how is it ? 
thanks .

**Comment by jimm98y** [comment]
For video stream you need some RTSP url. To get it, you have to use some IP camera, or SharpRealTimeStreaming RTSP server https://github.com/jimm98y/SharpRealTimeStreaming/tree/main/src/SharpRTSPServer. 
Then you have to update https://github.com/jimm98y/SharpOnvif/blob/main/src/OnvifService/Onvif/MediaImpl.cs and return your RTSP url from the GetStreamUri.

**Comment by masgh021** [comment]
Thanks @jimm98y 
I download rtsp server source and run it , it gives me this link rtsp://admin:password@127.0.0.1:8554 
I test link in vlc and worked , now I want add this link for live-video or live-streaming option in onvif sharponvif project, I don't know how update function and return this link. could you help ?    
Thanks.

**Comment by masgh021** [comment]
Hello @jimm98y 
I couldn't find how send stream url to Onvif device manager. 
do you have any sample ?

**Comment by jafar88A** [comment]
Hi @masgh021 
I have same Problem.

**Comment by jimm98y** [comment]
You have to put this URL here: https://github.com/jimm98y/SharpOnvif/blob/d2b26dd22b491d5a1a8335bb3e6df3b7c393c862/src/OnvifService/Onvif/MediaImpl.cs#L52C17-L52C61

**Comment by jimm98y** [comment]
The server sample now supports RTSP as well as PTZ from Onvif Device Manager.

**Comment by jimm98y** [comment]
There were a few more changes needed, not just the URL. See https://github.com/jimm98y/SharpOnvif/pull/15/files#diff-239792789ac25553aa399a86b2a342bcdb73d636a1403eea6f2355af71a0ae95. Please get the latest sources from this repo as they contain updated sample app.

**Comment by masgh021** [comment]
Thanks @jimm98y  this problem solved,
but I have new problem and when I connect another pc via LAN to my laptop and I start application but I couldn't  find my laptop in onvif device manager . what is the problem . (I can ping my laptop IP in CMD )

**Comment by masgh021** [comment]
Hello @jimm98y 
Do you have a solution?

**Comment by jimm98y** [comment]
Sounds like a networking issue. Onvif is using UDP broadcast for discovery and those UDP broadcast datagrams must be able to reach Onvif Server. You should check the IP in which Onvif Server is listening (in case you have multiple network interfaces, make sure it's using the same one as your "client". Also you might want to try disabling Windows Firewall and see if that fixes your problem.

**Comment by masgh021** [comment]
Thanks @jimm98y .

**Comment by eantunes1980** [comment]
Hi @jimm98y ,

thank you for the great project. 
Unfortunately I'm couldn't getting the Server running. Getting Authentication errors, Internal Server Errors,... 
Can you provide a sample of a Onvif-Server with one RTSP-Stream?

**Comment by jimm98y** [comment]
You need to be a more specific - what kind of authentication/internal server errors are you getting? Can you share the stack trace?

The sample with one RTSP stream is already in this repo: https://github.com/jimm98y/SharpOnvif/tree/main/src/OnvifService

The steps to run it locally:
1) clone this repo
2) run Visual Studio as Administrator
3) compile and run https://github.com/jimm98y/SharpOnvif/tree/main/src/OnvifService

If you want to also have RTSP, then:
1) clone https://github.com/jimm98y/SharpRealTimeStreaming
2) run Visual Studio as Administrator
3) compile and run https://github.com/jimm98y/SharpRealTimeStreaming/tree/main/src/RTSPServerApp

Now using Onvif Device Manager, you should see this server and you should also be able to see the RTSP stream.

**Comment by eantunes1980** [comment]
Thank you. I've tested the first example it's working. I will try to work with this sample. I havn't shared details because was searching a sample like that. Thank you, if I have other troubles I will share more details ;)
