### ISSUE TITLE
Error for authentication

### ISSUE THREAD

**Issue by masgh021** [jimm98y/SharpOnvif#5]
Hi @jimm98y 
yesterday application worked But today when I want to connect via onvif device manager , I've got this Error.  

Information: AuthenticationScheme: Digest was challenged.

can you help me to resolve this??  
thanks

![test4](https://github.com/user-attachments/assets/3c37cb95-1bc5-4c9a-a27d-f540910e4a2c)

**Comment by jimm98y** [comment]
You are not signed in the Onvif Device Manager. Enter your camera credentials on top in the Name/Password fields, click "Log In" and then try again.
